name: 'SARIF Courier'
description: 'A GitHub Action to render SARIF Security Reports right into your Pull Requests. Without the need for GHAS support!'
author: 'Abdullah Schahin'

branding:
  icon: 'shield'
  color: 'green'

inputs:
  sarif_file:
    description: 'Path to the SARIF file to process.'
    required: true
    default: 'results.sarif'
  


outputs:
  result:
    description: 'Result of the SARIF processing.'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--sarif'
    - '${{ inputs.sarif_file }}'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_REF: ${{ github.ref }}
    GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}